#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#
include $(TOPDIR)/rules.mk
LUCI_TITLE:=LuCI Multi User - LuCI Multi User Implimentation Version 1.00
LUCI_DEPENDS:=+luci-base +luci-mod-admin-full
include ../../luci.mk
# call BuildPackage - OpenWrt buildroot signature
